### ISSUE TITLE
Add JSON support

### ISSUE THREAD

**Issue by vorot93** [multiplay/qstat#10]
JSON has been implemented in [third party repo](https://github.com/eXprojects/qstat-json). Maybe merge this into upstream?

**Comment by illwieckz** [comment]
Yes, it's something I talk about with @stevenh last year, he saids he had pinged the owner for a pull request, so if today nothing was done, it means we must probably do it ourselves. If I remember, this repository (eXprojects) is not a fork from a repo but from a tarball archive, so this repo is missing some history, so there is some work to do by hand.

This is something I want to do since many months but I've never found the time to do it, cf. https://github.com/XQF/xqf/issues/12 . :wink:

**Comment by illwieckz** [comment]
See #13.
