### ISSUE TITLE
Servers with type 'xonotics' returning empty players randomly

### ISSUE THREAD

**Issue by morecofe** [multiplay/qstat#88]
Hi, that is a hard one to reproduce but you might be able by querying the same server several times or with intervals. While the returned result has 'numplayers' 7 for e.g. it randomly returns an empty array of players (regardless of a crowded server having more than 5 real players). Proven this happens when you type two commands consequently. Last command returns with retries:1 and players empty.

**Comment by illwieckz** [comment]
I wonder if it's an issue on xonotic side or not, for months I discovered that I get a timeout something like 90% of the time while querying xonotic servers. See my [server page that relies on `qstast`](http://gg.illwieckz.net/), the xonotic servers are usually displayed in orange with no information because of timeout.

**Comment by stevenh** [comment]
That sounds like a server side issue, have you tried increasing the timeout / retries!

**Comment by ndmrcf** [comment]
I confirm increasing retries to 5 helped (not the timeout) and returned players. I was expecting at least 'timeout' status when this failed but seems always 'online' when it happens.
